# example netlify.toml


[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "."

[dev]
  autoLaunch = false
  port = 5000
  targetPort = 5555

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]